# Generated by Django 6.0.1 on 2026-02-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartequ', '0002_chatuser_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatUser',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
