# Generated by Django 6.0.1 on 2026-02-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartequ', '0003_remove_message_user_delete_chatuser_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
